### ISSUE TITLE
Include max combo in /get_beatmaps

### ISSUE THREAD

**Issue by Tillerino** [ppy/osu-api#104]
Most of the time, there will be a perfect score in the top plays, so one can assume that it's combo is the max combo. When there isn't (hard maps, new maps), it's _really_ hard to figure out the max combo from the beatmap objects (sliders), so I'd love to just have a max combo field in the beatmap object.

**Comment by TheHowl** [comment]
Documented in https://github.com/peppy/osu-api/wiki/Home/_compare/f437cf07eed852c9a45ec879a6965f447930302d...2359c5634c01f22f0e5036038368845b1a924ebf

**Comment by CelegaS** [comment]
Is it possible for mania to have max hit instead of max combo (which is actually null)?

**Comment by vladyslavpron** [comment]
I'd like to see this in v2/users/{user}/scores/{type}

**Comment by Liam-DeVoe** [comment]
I'm not sure it's appropriate for a score to include the max combo achievable on the beatmap (scores do return a `beatmap` attribute, but it's a `BeatmapCompact` with `max_combo` null). If you require that information, you can make an extra api call to the `/beatmaps/lookup` endpoint to retrieve the max combo of the beatmap.

**Comment by vladyslavpron** [comment]
> I'm not sure it's appropriate for a score to include the max combo achievable on the beatmap (scores do return a `beatmap` attribute, but it's a `BeatmapCompact` with `max_combo` null). If you require that information, you can make an extra api call to the `/beatmaps/lookup` endpoint to retrieve the max combo of the beatmap.

Yep, I am exactly making extra api call to get this this data for my app, but would be nice if there were this field, so i musn't load osu servers for extra few requests.  
Still i think `max_combo` is same important for `BeatmapCompact` as `ar` or `drain` or stuff, it says a lot about map.
