### ISSUE TITLE
get_user for integral user names returns null

### ISSUE THREAD

**Issue by Tillerino** [ppy/osu-api#110]
This one is a bit funky. There are a couple of players who have an integral name, for example the player `14`. I need to stress that this is not their user *id*, but their user *name*. If you query their data via `https://osu.ppy.sh/api/get_user?k=KEY&u=14&type=string`, the response is `null`.

If you query an integral user name which does *not* exist, for example `https://osu.ppy.sh/api/get_user?k=KEY&u=2070907&type=string`, you get the usual *not found* response `[]`.

**Comment by peppy** [comment]
That user had a bugged username due to an admin-level username change (renaming them to two characters, which is invalid on osu!). I've reverted their username to three characters, so this error should now be resolved.

**Comment by Tillerino** [comment]
Oh it was about the length of the name.

Anyway, *should* the response for these short names be `null`? I feel like it should be the regular `[]` for *not found*.

**Comment by peppy** [comment]
There shouldn't be any other cases. This was an internal integrity check which should **never** be triggered.

**Comment by Tillerino** [comment]
It will never be triggered if you're only checking names which *exist*. However, right now the API behaves differently for a short name which doesn't exist (`null`) and a long name which doesn't exist (`[]`). That seems inconsistent.

**Comment by peppy** [comment]
How's that?

**Comment by Tillerino** [comment]
The naming constraints should not matter when looking for a username. All that should matter is if it exists or not. Take .com domains for example. They need to be at least two characters long. That's a simple constraint. `a.com` cannot be registered. But when I try to lookup `a.com` I get the regular *not found* message:

```
$ nslookup a.com
Server:		192.168.178.1
Address:	192.168.178.1#53

** server can't find a.com: NXDOMAIN

$ nslookup thisdomaintotallydoesnotexist.com
Server:		192.168.178.1
Address:	192.168.178.1#53

** server can't find thisdomaintotallydoesnotexist.com: NXDOMAIN
```

The current API behaviour would be equivalent to this:

```
$ nslookup a.com
Server:		192.168.178.1
Address:	192.168.178.1#53

UNSPECIFIED ERROR
```

**Comment by peppy** [comment]
By "how's that", I meant "could you please try again since I just made a fix for it"...

**Comment by peppy** [comment]
sorry, seems like you can't see the related commit. i thought they come up on the public page too

![](http://puu.sh/kTe1c/7645d9cdde.png)

**Comment by omkelderman** [comment]
> sorry, seems like you can't see the related commit. i thought they come up on the public page too

I think that happened once before ;) :P

**Comment by Tillerino** [comment]
Lol. I guess it's because the osu-web-10 repo isn't public.

Anyway, everything is looking good, thanks :)

**Comment by peppy** [comment]
sorry for the confusion!

**Comment by Tillerino** [comment]
I was a little confused that you were seeming to not get this consistency thing right away. Should have known.
