### ISSUE TITLE
get_replays for osu! does not work

### ISSUE THREAD

**Issue by Jazz914** [ppy/osu-api#124]
When using the following URL: 
https://osu.ppy.sh/api/get_replay?k={INSERT KEY HERE}&?m=0&?b=658127&?u=Cookiezi

It returns: 
{"error":"Replay not available."}

It works fine other modes.

**Comment by thehowl** [comment]
that's... not how you do it.
https://osu.ppy.sh/api/get_replay?k={KEY}&m=0&b=658127&u=Cookiezi -
without the other question marks.

**Comment by omkelderman** [comment]
lol, how did i not catch that xd, me trying to figure out what was going on for like 3 min... *facepalms*

**Comment by Jazz914** [comment]
I'm a fool, I have no idea how I managed to make this mistake. I even emailed peppy (Sorry!) - I thought something was wrong cause I could get it to work with mode 1, but I did that directly in the browser. When I wrote it in code form I guess I derped hard.

Thanks for that
