### ISSUE TITLE
aim, speed pp etc... values

### ISSUE THREAD

**Issue by thehowl** [ppy/osu-api#126]
with the open sourcing of osu-performance, peppy has dumped a database containing the ranked beatmaps in 2015's {aim, speed, ...} pp, generated by the diffcalc which seems to be, based on peppy's reddit comment, based in the osu! client. What I think would be better is that to provide this information through the osu! API, so that we can get the diffcalc information for every beatmap.

**Comment by peppy** [comment]
What's your intended use of the API endpoint?

**Comment by thehowl** [comment]
When I saw the open sourcing of osu-performance, I thought about making a tool that would calculate, using parts of the osu-performance source, the amount of PP of a replay until a certain point of the map, showing e.g. "how many PP I should have obtained without considering the song after the miss". Perhaps even making it possible to calculate PP of a hand-crafted score (e.g. "I start with all circles being 300, then I move a few of them to the 50 count, then add some misses", etc). Kinda like an "advanced tillerino".

**Comment by insomnyawolf** [comment]
I like the idea :+1: Vote up here

**Comment by omkelderman** [comment]
@thehowl you actually already can kinda do that, you can request pp amounts for certain mod/combo/misses combination with `!acc` (last one in https://github.com/Tillerino/Tillerinobot/wiki)

**Comment by Numbermaniac** [comment]
@omkelderman but that's only for standard, what if I want it for a different gamemode?

**Comment by omkelderman** [comment]
@Numbermaniac true, I wasnt really saying its a replacement or something, merely commenting on the "advanced tillerino"-comment of thehowl :stuck_out_tongue: (notice the `kinda`)

**Comment by Slayer95** [comment]
This would be great to externally perform bivariate analysis between map difficulty and accuracy from user's top plays, as raised in https://github.com/ppy/osu/issues/4680. Without this feature, I'm forced to download and parse every beatmap to calculate the map difficulty.

For my use case, I'd ideally request this information to be included within ``get_user_best``, but including it in ``get_beatmaps`` or making it an exclusive API endpoint would be great approaches too.

**Comment by peppy** [comment]
Just to confirm, you're after the raw difficulty values of the *beatmap*, not the user scores, right?

**Comment by Slayer95** [comment]
I require the difficulty values of the beatmap *after* applying mods.

**Comment by Slayer95** [comment]
Of course, if -as it seems to be the case- those can be calculated as a function of the unmodded difficulty values and the mods used, that task can be left to the API user (just like it's done with the accuracy of a score).

**Comment by peppy** [comment]
If you're capable, there are several ways of doing this locally already, the most current (in development) being to use https://github.com/ppy/osu-difficulty-calculator. Note that this is a WIP and only viable for osu! mode for now.

**Comment by Slayer95** [comment]
> Without this feature, I'm forced to download and parse every beatmap to calculate the map difficulty.

I am using https://github.com/Francesco149/ojsama for that, yeah.

> that task can be left to the API user

> doing this locally

IIUC from [calculator](https://github.com/ppy/osu/blob/9cbd3f43f3af66a893d172f813d10b6a10b118d7/osu.Game.Rulesets.Osu/Difficulty/OsuDifficultyCalculator.cs#L33-L34), it's trivial to get the modded difficulties from the unmodded ones.

However, getting the later unavoidably requires parsing maps for now, which is what I'd hope the osu! API solves.

---------
Sorry for not being very clear in previous comments... The scope of this issue, my use case and my request don't seem to 100% match, as I'd like to request the minimum featureset possible. So to sum it up:

*Please provide base ``aimRating`` and ``speedRating`` to empower API consumers and enable direct calculation of modded map difficulties from the map metadata.*

**Comment by peppy** [comment]
Please check this behaves as you expect and update the wiki documentation if so.

```json
        "passcount": "51352",
        "max_combo": "439",
        "diff_aim": "2.302056312561035",
        "diff_speed": "1.9515023231506348",
        "diff_strain": "4.428835868835449",
        "difficultyrating": "4.428835868835449"
    },
```

- option parameter mods=x will return values for a specific mod combination.

**Comment by Slayer95** [comment]
Thanks!

Some values of ``mods`` seem to be unsupported. Tried with ``8``, ``8 + 16``, ``8 + 16 + 64`` (HD, HDHR, HDHRDT)

Those include 
```js
{
"max_combo": null,
"diff_aim": null,
"diff_speed": null,
"diff_strain": null,
"difficultyrating": "0"
}
```

**Comment by peppy** [comment]
If nulls are returned for certain mod combinations, it usually means they are unaffected by the mod. This is best-effort (we only store combinations as required to save on database).

aka intended behaviour.

**Comment by Slayer95** [comment]
The fact that ``max_combo`` is nulled too is baffling tbh. But I guess it's just a documentation issue.

**Comment by peppy** [comment]
I'd recommend not specifying mods in most cases. I only added the mod argument as an option for very edge-case usage. I wouldn't recommend, for instance, iterating over each mod combination on the API. You should be doing this locally as specified above. It's more efficient.

**Comment by ThePooN** [comment]
In osu!mania, Key1, Key2 and Key3 report `null` values, despite them having an impact on the star rating. Probably a side effect of them being unranked mods.

It also seems like difficultyrating is way off in osu!mania on converts, with all mods combinations. But this also affects the website, so it sounds like a seperate issue.

**Comment by peppy** [comment]
I'd still strongly recommend calculating locally where possible, although i can't yet recommend that for mania since the implementation is incomplete
