### ISSUE TITLE
API too slow?

### ISSUE THREAD

**Issue by Piotrekol** [ppy/osu-api#13]
"Current rate limit is set at an insanely high 1200 requests per minute"
That's what is written in docs.
But it doesn't seem like it's correct. Using my updater(osuStats) script I can get at most 200maps(requests)/1min with is way lower ratio than in docs. (Now update takes about 9-10hrs(all modes) instead of ~30-40mins before API keys were introduced- no changes were made in my script(only hardcoding apikey))

**Comment by tigerw** [comment]
Three years on... I wonder if anyone realised that @Piotrekol was actually saying that they made a *mistake* of using `.php` instead of unsuffixed and corrected that, rather than the other way round as @peppy interpreted.

**Comment by Cyanoure** [comment]
> Three years on... I wonder if anyone realised that @Piotrekol was actually saying that they made a _mistake_ of using `.php` instead of unsuffixed and corrected that, rather than the other way round as @peppy interpreted.

Same thing 10 years later 🤣
