### ISSUE TITLE
maxCombo == null?

### ISSUE THREAD

**Issue by Tillerino** [ppy/osu-api#130]
`https://osu.ppy.sh/api/get_beatmaps?k=...&b=378344` returns

```
[{
 "beatmapset_id":"144171",
 "beatmap_id":"378344",
 "approved":"1",
 ...,
 "mode":"0",
 ...,
 "max_combo":null,
 ...
}]
```

There are a bunch of graveyard maps with the same problem.

**Comment by peppy** [comment]
Probably means the maps themselves are very broken (and can't be processed by osu!). Probably best to consider the map unplayable in this case.

**Comment by omkelderman** [comment]
is it an idea to document this?

**Comment by peppy** [comment]
either that or just nuke the maps (remove from our system completely).

i'll keep this issue open until we've done something more permanent.

**Comment by MillhioreF** [comment]
This seems to happen when the .osu file is missing from the server. In the case of graveyarded maps it's probably a bad upload and can be safely nuked, but the ranked map mentioned here (378344) broke after a hax submit and should probably be fixed manually (the proper file is still in the osz)

**Comment by iebb** [comment]
same problem with 463204 :(

**Comment by peppy** [comment]
For personal reference:

https://gist.github.com/31621d1172c0a7faacf6248aba728e47
`beatmap_id actual_checksum db_checksum`

Will be looking into this over the next few days, when I find a spare moment.

**Comment by Blobfisherinno** [comment]
Well, how come my map whatever I do is corrupted?

https://osu.ppy.sh/s/657926

Does that seem unplayable to you... ._. at least I'm able to launch and play it

**Comment by SarahIsWeird** [comment]
This also applies to all Taiko maps I tested. Either they give a wrong max combo or flat out null.
`1956103 -> null`
`1955893 -> null`
`1661873 -> null`

Interestingly enough, K.O.K.O.R.O., the last ID, also had the same issue with mania difficulties.
`1640396 -> null`

**Comment by peppy** [comment]
I believe max combo is only being populated for osu! beatmaps for now. This is due to osu! using a newer version of the processor. Other rulesets will be included as we apply new score processing algorithms and upgrade them to using lazer as the processor.

**Comment by peppy** [comment]
Closed via https://github.com/ppy/osu-api/issues/267
