### ISSUE TITLE
URL Resolve

### ISSUE THREAD

**Issue by oopsjpeg** [ppy/osu-api#136]
I think there should be a way to determine what a link is supposed to direct to through the API. For instance, using `/api/resolve?k=KEY_HERE&url=http://osu.ppy.sh/u/oopsjpeg` should return a JSON containing the key "type" with the value of "user", as well as the username and user ID. Using `/api/resolve?k=KEY_HERE&url=https://new.ppy.sh/beatmapsets/488619` should return the type "beatmapset" as well as the beatmap set's ID.

**EDIT**: If the URL is something that the API doesn't know about, it could return "unknown" or "error".

**Comment by omkelderman** [comment]
cant you just parse the url yourself and call the appropriate api-endpoint? seems kinda out of scope for api to me...
