### ISSUE TITLE
/api/get_replay: not working?

### ISSUE THREAD

**Issue by archerdrag10** [ppy/osu-api#138]
I can't seen to retrieve any data from `/api/get_replay` anymore. Was there something I missed? Does it work for anyone else? I get the following every time:

{"error":"Replay retrieval failed."}

**Comment by peppy** [comment]
Can you give a sample API request URL you expect to work (without the API key)?

**Comment by archerdrag10** [comment]
https://osu.ppy.sh/api/get_replay?k=KEYHERE&m=0&b=867819&u=Cookiezi

This should work correct?

Map in question: https://osu.ppy.sh/b/867819&m=0

**Comment by peppy** [comment]
Thanks. Could you please try again?

**Comment by archerdrag10** [comment]
Just retried. Same problem:

{"error":"Replay retrieval failed."}

**Comment by peppy** [comment]
Please try once more!

**Comment by archerdrag10** [comment]
It works! Thanks.
