### ISSUE TITLE
get_user_recent not working for me

### ISSUE THREAD

**Issue by RobBednark** [ppy/osu-api#151]
I just started using the API, and am able to successfully call three of the endpoints.  However, `/get_user_recent` is returning an empty list:

```
$ curl 'https://osu.ppy.sh/api/get_user?k=<my_key>&u=Cookiezi'
[{"user_id":"124493","username":"Cookiezi","count300":"4832097","count100":"192331","count50":"15603","playcount":"12111","ranked_score":"18323807858","total_score":"105905001611","pp_rank":"1","level":"100.79","pp_raw":"13009.1","accuracy":"98.77983856201172","count_rank_ss":"51","count_rank_s":"376","count_rank_a":"281","country":"KR","pp_country_rank":"1","events":[]}]

$ curl 'https://osu.ppy.sh/api/get_user_recent?k=<my_key>&u=Cookiezi'
[]
```

Am I doing something wrong?

**Comment by shARPIII** [comment]
It is working, it just doesn't tell you it takes recent plays from the last 24 hours. Cookiezi has none, try with someone else.

Also use "limit" if you want to have more than 10 records. 
You will also have failed plays contrary to the new website which display every not failed plays in the last 24 hours. You might not have every plays which are displayed on the website in the recent tab.

**Comment by RobBednark** [comment]
Thank you @shARPII !  I got it working now with a different user.
