### ISSUE TITLE
Loved maps do not appear in get_beatmaps?since=...

### ISSUE THREAD

**Issue by Kert** [ppy/osu-api#152]
Please fix this.
Thank you

**Comment by omkelderman** [comment]
sure, but you missed the point SpiderNight was making: `since` is for getting beatmaps that are **ranked** since X date, and loved *is not* ranked. "having a scoreboard" does not equals to "being ranked".

**Comment by Kert** [comment]
Approved maps also work when `since` is used, so

**Comment by omkelderman** [comment]
oh kek, did not know that xd

**Comment by jxu** [comment]
btw this is fixed
