### ISSUE TITLE
Multiple *ranked* scores being returned in get_user_best

### ISSUE THREAD

**Issue by SpiderNight** [ppy/osu-api#154]
As shown here: http://i.imgur.com/eiQWz4E.png
This user, zz-e, improved their top score and instead of getting overwritten, it was just slapped on top. I haven't done testing to see if the pp from both is included in the player's net pp but it may.

Probably a side effect of the loved maps multiple scores implementation?

**Comment by omkelderman** [comment]
> Probably a side effect of the loved maps multiple scores implementation?

`enabled_mods` is different for both of them (one is covered up in that search thing in your screenshot, but I looked it up myself), so I would guess yes

**Comment by SpiderNight** [comment]
It shows in the api call, but not in the user's profile so I assume its a bug. Also if it does affect pp with both, then HD players essentially can just do non HD versions of all their scores now so it must be a bug

**Comment by Tom94** [comment]
This is a display bug, pp does not take into account multiple scores on the same map. Only the one that gives most pp.

**Comment by SpiderNight** [comment]
Even with it being a display bug, is it going to be fixed soon? I assume it is a pretty big issue to many projects including osu!chan.

**Comment by omkelderman** [comment]
confirmed fixed :ok_hand:
