### ISSUE TITLE
Suggesting adding an option to fetch beatmap picture

### ISSUE THREAD

**Issue by MeLikeChoco** [ppy/osu-api#162]
Although some songs have multiple pictures, it would be nice to still be able to get a link to a picture used in the song/beatmap.

**Comment by ekgame** [comment]
I don't think that high quality background is stored separately from the beatmap.

**Comment by MeLikeChoco** [comment]
But it IS there when you view it on the beatmap list.

**Comment by ekgame** [comment]
The covers on the new beatmap page are low quality and cropped.

**Comment by MeLikeChoco** [comment]
That's fine, just some picture.

**Comment by omkelderman** [comment]
well, not necessarily part of api, but you could just fetch `https://b.ppy.sh/thumb/<beatmap-set-id>l.jpg`. (note: *set*-id, not beatmap-id.) If you omit the `l` you get an even smaller picture. It'll probably work for every beatmap.

**Comment by MeLikeChoco** [comment]
If it can pull those images, surely it can pull a bigger one? Sigh.

**Comment by SpiderNight** [comment]
There are the cover pictures for the new site: https://assets.ppy.sh//beatmaps/BEATMAP_ID/covers/cover.jpg

Not full pictures but they are better quality.

**Comment by MeLikeChoco** [comment]
That's excellent. Why aren't these documented anywhere?

**Comment by peppy** [comment]
because they are not intended for use outside of the new site.
