### ISSUE TITLE
Option to fetch url of user's profile picture? Possibly banner? /api/get_user

### ISSUE THREAD

**Issue by MeLikeChoco** [ppy/osu-api#163]
Or return null for them if there is none present?

**Comment by SpiderNight** [comment]
Avatar: https://a.ppy.sh/USER_ID
What do you mean by banners? The new sites user uploaded cover pictures for supporter? I don't think there is a good way of fetching those.

**Comment by GrilledCheeese** [comment]
I would like this for **USER COVER IMAGES**:
![image](https://user-images.githubusercontent.com/34809632/82919962-fc88c300-9f76-11ea-9dfd-83ea1199fe8d.png)
![image](https://user-images.githubusercontent.com/34809632/82920155-3954ba00-9f77-11ea-8510-fb315f446b23.png)

**Comment by peppy** [comment]
user covers are provided via apiv2 already.
