### ISSUE TITLE
/api/get_match documentation

### ISSUE THREAD

**Issue by Borengar** [ppy/osu-api#164]
get_match returns a 0 for "pass" in "scores" according to the documentation if a player failed at least once. Observed behavior is that a 1 is returned if a player revives after failing before the end of the map.
Please fix the documentation in that regard.

**Comment by thehowl** [comment]
The best place where you can find a helping hand [is at the end of your arm](https://github.com/ppy/osu-api/wiki/Home/_edit).

**Comment by Borengar** [comment]
Sorry didn't expect that everyone had edit rights.
