### ISSUE TITLE
osu.ppy.sh/api/get_user/ takes me to the github page?

### ISSUE THREAD

**Issue by runnerbeany** [ppy/osu-api#167]
Can someone tell me what's wrong?
`http://osu.ppy.sh/api/get_user/?u={0}k=key', type=username).format(query)`
doing this in python.

**Comment by ekgame** [comment]
`get_user/?` remove the slash and it should work.

**Comment by runnerbeany** [comment]
It's fixed something. I'm now greeted with `{"error":"Please provide a valid API key."}`

**Comment by ekgame** [comment]
It looks like you're missing the `&` sign between arguments

**Comment by runnerbeany** [comment]
Ahh. Got it working. Thank you!
