### ISSUE TITLE
Beatmap files for FOLiACETATE - Heterochromia Iridis are empty

### ISSUE THREAD

**Issue by Tillerino** [ppy/osu-api#171]
All beatmap files in the set https://osu.ppy.sh/s/106443 are empty. Select any beatmap in the set and click 'grab latest .osu file'. [Example](https://osu.ppy.sh/osu/279481)

**Comment by omkelderman** [comment]
I have done some experimenting/analysis and I have found this list of beatmap-ids of which the 'grav latest .osu file'-file doesnt match the `file_md5` property in the API:

> 1021815
> 1047560
> 197279
> 275266
> 279481
> 279607
> 280043
> 280445
> 280867
> 378344
> 616659
> 621903
> 621907
> 621905
> 672240
> 732724
> 735432
> 762231
> 777867
> 777875
> 871542
> 893209

**Comment by Tillerino** [comment]
Another list:

**Comment by peppy** [comment]
All of these have been fixed.

**Comment by Liam-DeVoe** [comment]
I think the same issue occurs with this set https://osu.ppy.sh/beatmapsets/479215, when going to `https://osu.ppy.sh/osu/{map_id}` on any map in the set I get a blank page and no download. Not sure if that's the behavior people saw here previously, or if an empty .osu file was actually downloaded. Either way this set has broken downloads

**Comment by peppy** [comment]
That's a graveyard beatmap, not sure we are going to start fixing those (is this causing an issue for you somewhere?)

**Comment by Liam-DeVoe** [comment]
I think the beatmap 1242897 in particular of that set was used for OWC 2019 Quarterfinals NoMod (as seen in the set description) and so some replays set on that map are of interest for analysis using [circleguard](https://github.com/circleguard/circleguard), which relies on automatically downloading maps when visualizing the replay. I understand if you're not willing to fix unranked/unloved beatmaps though.

**Comment by peppy** [comment]
I see. Can make an exception for this one I guess, but not sure it will be a common thing (or something we aim to fix 100%).

**Comment by Ephemeralis** [comment]
https://osu.ppy.sh/beatmapsets/479215 has been fixed.
