### ISSUE TITLE
Feature request: search for beatmaps by name

### ISSUE THREAD

**Issue by christopher-dG** [ppy/osu-api#173]
I wrote a [reddit bot](https://github.com/christopher-dg/osu-map-linker-bot) that gets beatmap links from score posts but it needs to look at the player's recent plays to get the beatmap ID which isn't quite as reliable as it could be. It would be much easier if I could search by beatmap/song name, the same way you can on the main website.

**Comment by omkelderman** [comment]
#5 #127

**Comment by christopher-dG** [comment]
@omkelderman Sorry, thanks for pointing those out.
