### ISSUE TITLE
Download full .osr files

### ISSUE THREAD

**Issue by christopher-dG** [ppy/osu-api#174]
Is there a reason that the files downloaded from `/api/get_replay` are missing the LZMA portion? It would be great to get the cursor and keyboard data as well to do replay analysis.

**Comment by omkelderman** [comment]
uuhm, the data from the `/api/get_replay` endpoint *is* the LZMA portion, nothing more, nothing less...

also
> the files downloaded from

there is no file, its only the LZMA-part ^^

**Comment by christopher-dG** [comment]
Yeah I phrased that badly. The wiki is worded somewhat strangely, by "the remaining data" I thought it meant "the data that's missing". 

So then if we can match that data with the data from `/api/get_scores` for example, would you be able to construct a full replay?

**Comment by omkelderman** [comment]
that "remaining data" part on the api-wiki is a quote taken from the osr-file-format page on the osu wiki. There it talks about the content of an osr-file, which ends (hence "remaining") with the LZMA-data, which is the (only) part you get from the API.

I am responsible for that api-wiki edit that added that section to the api-wiki, so if that is not clear, I guess I'll have to maybe edit that...

**Comment by christopher-dG** [comment]
Yeah even just an explicit "The data returned by the endpoint is the LZMA stream referred to by the wiki here: <quote>.

Also, I found your replay downloader and it works great so it solves my problem!

**Comment by omkelderman** [comment]
edited the wiki again

> Also, I found your replay downloader and it works great so it solves my problem!

nice :smile:, so uhm, I guess we can close this issue here? :stuck_out_tongue:

(if there are any problems with the replay downloader, be sure to let me know there!)

**Comment by christopher-dG** [comment]
Yeah, so far so good with the downloader, I'll just link your project for anyone reading in the future.

https://github.com/omkelderman/osu-replay-downloader
