### ISSUE TITLE
Can i download .osz from api (after my user log in)

### ISSUE THREAD

**Issue by EdrowsLuo** [ppy/osu-api#176]
i am buliding a new android app to download beatmaps,and maybe some beatmaps i have to download from osu.ppy.sh,but i can't get a way to achieve it :(

ps: i can let my user log in to download beatmaps

**Comment by ekgame** [comment]
As far as I know Android has Apache HttpClient. As long as you use the same client instance for all requests, you can login and download beatmap archives. 

If you don't need the full archive, you can download `.osu` files without logging in.

**Comment by omkelderman** [comment]
> If you don't need the full archive, you can download `.osu` files without logging in.

Dont count too much on that one tho, you dont wanna know how much "empty beatmap file" errors are getting spammed in tillerinobot-log ^^
