### ISSUE TITLE
beatmap id 1258033 (Loved, Aspire) isn't represented in get_beatmaps output

### ISSUE THREAD

**Issue by Piotrekol** [ppy/osu-api#183]
Beatmap is for some reason simply missing in api.
I've tried using following urls:
https://osu.ppy.sh/api/get_beatmaps?k=key&since=2017-04-03%2000:00:00
https://osu.ppy.sh/api/get_beatmaps?k=key&b=1258033

First one returns maps like intended, except for that beatmap.
Second one just returns empty array

**Comment by ThePooN** [comment]
Can confirm

**Comment by peppy** [comment]
This should be resolved. Please follow-up in this thread if you are still experiencing issues.

**Comment by ThePooN** [comment]
https://osu.ppy.sh/api/get_beatmaps?k=key&b=1258033 stills returns [] here.

**Comment by omkelderman** [comment]
can confirm

**Comment by peppy** [comment]
Aha, this was a completely different issue, related to that map breaking all difficulty calculations.

I've inserted a token star difficulty of zero and it should now be returned as expected.

**Comment by omkelderman** [comment]
can confirm i'm getting a beatmap-object response :ok_hand: 👍

**Comment by ThePooN** [comment]
Works! Thanks for addressing this fast 👍
