### ISSUE TITLE
i want to get osump://id/,but get_match haven't it...

### ISSUE THREAD

**Issue by lslqtz** [ppy/osu-api#186]
think about adding it?

**Comment by Jeremiidesu** [comment]
doesn't this url scheme have a short id number (4-5 digits or so) ? if so, then it simply won't work, because when the lobby is closed, then this id becomes invalid. the only way is to use the mp link id.

**Comment by lslqtz** [comment]
yep,but i hope i can get this osump://id/ link...ecause of me and my friends hope send osump link to #lobby and custom link text, but use /invite always prompt the user is not currently online...
if haven't,I think it can doesn't show...

**Comment by Jeremiidesu** [comment]
well, as a workaround you can still invite yourself to your game. i usually do that in case i kick myself out of the game, but i guess it can still work if you want to copy this url

**Comment by lslqtz** [comment]
but i can't invite me...user is not currently online again

**Comment by Jeremiidesu** [comment]
wait, my username is Jeremiidesu in game. That way, I type `/invite
Jeremiidesu` in chat and I get an invitation to myself and it works
everytime. Something has to be wrong with your account or game if you cant
do that

**Comment by Jeremiidesu** [comment]
wait, my username is Jeremiidesu in game. That way, I type `/invite Jeremiidesu` in chat and I get an invitation to myself and it works everytime. Something has to be wrong with your account or game if you cant do that

**Comment by lslqtz** [comment]
thank you! I found the correct use,I thought it was in the corresponding chat to use /invite... and /help can't find <user>...
