### ISSUE TITLE
Individual multiplayer scores not including mods/accuracy from /get_match

### ISSUE THREAD

**Issue by Jeremiidesu** [ppy/osu-api#189]
```json
{
  "slot": "0",
  "team": "0",
  "user_id": "8670458",
  "score": "1181315",
  "maxcombo": "116",
  "rank": "0",
  "count50": "4",
  "count100": "137",
  "count300": "714",
  "countmiss": "52",
  "countgeki": "88",
  "countkatu": "67",
  "perfect": "0",
  "pass": "0"
}
```
(full API return at https://pastebin.com/pCg4cGcZ . Call issued when only the first map of [this](https://osu.ppy.sh/mp/34131242) match was played.)

Currently, the individual multiplayer score doesn't return the Freemod chosen mods. In the example game provided above, I (first line) used HD and the other player used HR. Currently there is no way for me to know that.

I planned to use that to make a program capable of displaying the matches from a multiplayer match in a convenient way, like this:
![example](https://d3l2vgu4vowu3r.cloudfront.net/Jeremdesu/Uploads/2017-06-26_23-38-18.png)
Other applications (such as a tourney management tool i'm developing) could benefit as well from this, when displaying freemod tournament picks.

The accuracy isn't returned either, and in my opinion, including it would help. As a workaround I can calculate it myself though.

**Comment by willyosu** [comment]
I don't think any other request for plays returns a solid "accuracy" number anyway, so as long as you have the hits you should just calculate it. Accuracy is just a ratio of the hits to the sum of all hits (300s being worth a whole hit, 100s being 1/3, 50s being 1/6, and misses being 0) so you can easily get the accuracy using:

`accuracy = ( count300/1 + count100/3 + count50/6 ) / ( count300 + count100 + count50 + countmiss)`

As for the freemod mods, that is a good catch and I hope it gets added.

**Comment by julialuongw** [comment]
Has this ever been acknowledged by any of the devs?

**Comment by breadbyte** [comment]
No. This is the only correspondence with this issue that we have.

**Comment by peppy** [comment]
I've added enabled mods to the response.
