### ISSUE TITLE
/api/get_user_recent returns no data

### ISSUE THREAD

**Issue by khazhyk** [ppy/osu-api#191]
Responds with [] for all queries

**Comment by peppy** [comment]
Is this a recent development? As in did you used to get different results?

**Comment by khazhyk** [comment]
I'm not sure how recent, but you used to be able to get a user's recent scores.

I tried myself, cookiezi, and also completely invalid parameters (exepecting a parse error), and always got []

**Comment by peppy** [comment]
Have you actually played anything recently?

**Comment by khazhyk** [comment]
https://osu.ppy.sh/u/cookiezi has played most recently 7 hours ago and has many entries in recent activity

**Comment by peppy** [comment]
this isn't recent activity endpoing. this is recent plays. it only returns 24 hours.

**Comment by khazhyk** [comment]
Ah, thanks. The 24-hr limit isn't documented, wrongly assumed it was similar to the recent activity limit.

**Comment by peppy** [comment]
I updated the documentation
