### ISSUE TITLE
Providing song name/title of beatmap in get_user_best & get_user_recent

### ISSUE THREAD

**Issue by 21Joakim** [ppy/osu-api#192]
I would like to request that the song name/title of a beatmap is sent together with the data in get_user_best & get_user_recent.

This would, at least in my case, remove the requirement to make 10 extra request to get the title of each beatmap.

Side note, why is the username provided in get_user_best but not in get_user_recent?

**Comment by peppy** [comment]
Those 10 requests should be cached at your end so they only need to be made once. Are you doing this?

**Comment by peppy** [comment]
Also you make a good point: the username should probably be removed in said case.

**Comment by 21Joakim** [comment]
I know that from your point of view this does not make sense, to provide said data which is already provided in another request, therefore I actually doubt you will implement anything like this but from my point of view I would not have to make those 10 requests at all if the title was provided.

Only wish there was a querying system in place where you could choose yourself what data should be provided. (Benefits of this would be that if used correctly by the user the load on the server and or client would be reduced and it would also provide a fully customizable way to request data to fit the needs of their application(s).)

**Comment by 21Joakim** [comment]
Not sure if the username was actually provided, I took it for granted when it said so on the wiki but upon actually making the request I realized that it was not provided. (One possibility is that you already removed it.) I edited the wiki and removed the part where it said that the username was provided for /api/get_user_best

**Comment by peppy** [comment]
When used correctly, caching (as i recommended) reduces server load. Not what you are asking for.
