### ISSUE TITLE
Get all info about ranked/loved maps?

### ISSUE THREAD

**Issue by jxu** [ppy/osu-api#193]
Apologies if this has been asked before. Is there any way to get information about all ranked/loved maps other than starting at the first ranked map, getting 500, finding the last date, and looping? I am trying to gather some beatmap statistics.

**Comment by jxu** [comment]
Ok ever since https://data.ppy.sh/ this info can be downloaded.

**Comment by Liam-DeVoe** [comment]
The dump there only includes ranked maps ranked before `2018_05_28` though, right?

**Comment by jxu** [comment]
I thought so too. But 2020_03_01_performance_osu_top actually contains a whole bunch of tables, including osu_beatmaps.sql which as far as I can tell contains info for every ranked/loved (maybe pending) map. These are the files included:

```
./osu_difficulty_attribs.sql
./osu_beatmap_difficulty_attribs.sql
./sample_users.sql
./osu_counts.sql
./osu_beatmaps.sql
./osu_scores_high.sql
./osu_user_stats.sql
./osu_user_beatmap_playcount.sql
./osu_beatmap_failtimes.sql
./osu_beatmap_difficulty.sql
./osu_beatmap_performance_blacklist.sql
./osu_beatmapsets.sql
```
