### ISSUE TITLE
Negative value for count_rank_a

### ISSUE THREAD

**Issue by 21Joakim** [ppy/osu-api#194]
/api/get_user provides a negative value for count_rank_a for the following user,
User Id : 7792942
Username : Chilly-

**Comment by 21Joakim** [comment]
Jumped down to -3 now

Providing data if it jumps down any further :
`[{"user_id":"7792942","username":"Chilly-","count300":"8631452","count100":"1157510","count50":"55969","playcount":"12858","ranked_score":"750271612","total_score":"5331019238","pp_rank":"1999","level":"91.9915","pp_raw":"7940.69","accuracy":"94.13018798828125","count_rank_ss":"11","count_rank_s":"808","count_rank_a":"-3","country":"SE","pp_country_rank":"15","events":[{"display_html":"<img src='\/images\/A_small.png'\/> <b><a href='\/u\/7792942'>Chilly-<\/a><\/b> achieved rank #69 on <a href='\/b\/1294900?m=3'>Zekk - Swampgator [Wasteland Predator]<\/a> (osu!mania)","beatmap_id":"1294900","beatmapset_id":"613792","date":"2017-08-04 07:26:29","epicfactor":"1"},{"display_html":"<img src='\/images\/S_small.png'\/> <b><a href='\/u\/7792942'>Chilly-<\/a><\/b> achieved rank #643 on <a href='\/b\/941425?m=3'>Iced Blade - Sora no Senritsu -the melody of the cosmos- feat.lily-an (OP Cut) [4K Insane]<\/a> (osu!mania)","beatmap_id":"941425","beatmapset_id":"437171","date":"2017-08-04 07:12:39","epicfactor":"1"},{"display_html":"<b><a href='\/u\/7792942'>Chilly-<\/a><\/b> has submitted a new beatmap \"<a href='\/s\/648962'>Zekk - Hatsukoi Memories<\/a>\"","beatmap_id":"0","beatmapset_id":"648962","date":"2017-08-04 04:23:10","epicfactor":"4"},{"display_html":"<img src='\/images\/X_small.png'\/> <b><a href='\/u\/7792942'>Chilly-<\/a><\/b> achieved rank #147 on <a href='\/b\/1211270?m=3'>Gom (HoneyWorks) - Zen Zen Zense [4K Normal]<\/a> (osu!mania)","beatmap_id":"1211270","beatmapset_id":"571547","date":"2017-08-04 03:19:33","epicfactor":"1"},{"display_html":"<img src='\/images\/A_small.png'\/> <b><a href='\/u\/7792942'>Chilly-<\/a><\/b> achieved rank #809 on <a href='\/b\/797527?m=3'>Spawn of Possession - Apparition [Duty to God]<\/a> (osu!mania)","beatmap_id":"797527","beatmapset_id":"363184","date":"2017-08-03 23:30:15","epicfactor":"1"},{"display_html":"<img src='\/images\/S_small.png'\/> <b><a href='\/u\/7792942'>Chilly-<\/a><\/b> achieved rank #644 on <a href='\/b\/1192532?m=3'>RIN - Pluto -Tenderness [Hades Wrath]<\/a> (osu!mania)","beatmap_id":"1192532","beatmapset_id":"430938","date":"2017-08-03 23:19:58","epicfactor":"1"}]}]`

**Comment by wxv** [comment]
What's listed here is negative too https://osu.ppy.sh/p/pp?s=3&o=1&c=SE&find=Chilly-&m=3#jumpto
