### ISSUE TITLE
any way to calculate accuracy by osu-api?

### ISSUE THREAD

**Issue by valenok146** [ppy/osu-api#198]
Hello, Im writing extension for myself, and I cant find value of accuracy on any map passed by user.
So I could calculate it by amount of '**"count50", "count100", "count300", "countmiss", "countkatu", "countgeki"**'. (got it from 'api/get_scores')
So my calculations were wrong and the final value differs from the value on the site.
I request here for formula, which uses your api (yes, i've seen osu!accuracy on osu.ppy.sh)

**Comment by omkelderman** [comment]
peppy has said here https://github.com/ppy/osu-api/issues/182#issuecomment-294779540 that at some point accuracy will be included in the API response. But for now you should be able to get correct results by using the formulas on https://osu.ppy.sh/wiki/Accuracy

If you are using that and the values differs from the values on the site, then you might have an implementation error in your calculations.

**Comment by valenok146** [comment]
Okey, nevermind. Thx for answer.
