### ISSUE TITLE
Hit length and total length changed for DISCO PRINCE

### ISSUE THREAD

**Issue by Tillerino** [ppy/osu-api#205]
[An old regression test](https://github.com/Tillerino/osuApiConnector/blob/master/osuApiConnector/src/test/java/org/tillerino/osuApiModel/OsuApiBeatmapTest.java#L14) failed because the hit length and total length changed.

They used to be 108 and 141 respectively, now they are 109 and 142 respectively. What happened?

**Comment by peppy** [comment]
We increased lengths by one second to allow for the fact that old processing was `floor`ing the calculation when it shouldn't have been.

**Comment by Tillerino** [comment]
Alright, thanks for the reply.
