### ISSUE TITLE
count_rank_sh data incorrect.

### ISSUE THREAD

**Issue by Mother-Ship** [ppy/osu-api#206]
The value of count_rank_sh is simply equals the value of count_rank_s , instead of the the correct value.

**Comment by Adrriii** [comment]
For me (mania) it is equal to the SS number ; "count_rank_ss":"3460","count_rank_ssh":"13","count_rank_s":"1962","count_rank_sh":"3460","count_rank_a":"186"

**Comment by Jeremiidesu** [comment]
Same here:
```json
"count_rank_ss":"24",
"count_rank_ssh":"5",
"count_rank_s":"197",
"count_rank_sh":"24",
"count_rank_a":"196",
```
![My account at the time of the comment](https://d3l2vgu4vowu3r.cloudfront.net/Jeremdesu/Uploads/NLd2eqc16Mx.png)
(that's standard)
