### ISSUE TITLE
Increase get_replay limit

### ISSUE THREAD

**Issue by wxv** [ppy/osu-api#212]
The current limit is [10 requests per minute](https://github.com/ppy/osu-api/wiki#apiget_replay). This is unreasonable. A typical replay file might be ~40kB and a typical beatmap may be 5 MB. So, not counting server response resources, downloading a single beatmap takes about the same bandwidth as downloading 125 replays. And consider how many beatmaps are downloaded by users in a minute. 

I propose greatly increasing the current `get_replay` limit. Replays are very useful in determining cheated scores.

**Comment by peppy** [comment]
Each of these lookups is quite expensive. Apart from making this a paid service, I cannot increase the limit for now, sorry.
