### ISSUE TITLE
Add availability to /api/get_beatmaps

### ISSUE THREAD

**Issue by zinsserzh** [ppy/osu-api#219]
Can we add `availability` to /api/get_beatmaps so that we can know if a beatmapset has been removed due to copyright issues? Currently, there is no way to get this information other than crawling the web.

**Comment by geotim90** [comment]
Resolved with #241 ?

> **peppy commented on 4 Jun**
> Addded `audio_unavailable` and `download_unavailable`

**Comment by peppy** [comment]
Yep!
