### ISSUE TITLE
Add parameter to get beatmap set by its name

### ISSUE THREAD

**Issue by ghost** [ppy/osu-api#220]
This be helpful people who are searching a beatmap by its name, rather by its ID since most people search a beatmap by its name on the osu! site. Similar to how `get_user` uses a string or ID.

**Comment by ghost** [comment]
Attached is an image of how this feature would be used. Instead of a user searching by a beatmap set's ID they can type in a name.

**Comment by uzervlad** [comment]
You can use `/beatmapsets/search`, but you need to log in through `POST https://osu.ppy.sh/forum/ucp.php`

**Comment by ghost** [comment]
What should I post to this endpoint?

**Comment by uzervlad** [comment]
```js
formData: {
  login: "Login",
  username: "OctopuSSX",
  password: "yikes"
}
```

**Comment by ghost** [comment]
Thanks for the information, this thread was opened for a while. I'll be putting this to good use
