### ISSUE TITLE
/api/get_user[0].play_time

### ISSUE THREAD

**Issue by ghost** [ppy/osu-api#221]
I'm aware that the overall playtime isn't officially available through the osu! API right now. Looking through the source code of the new website, a user JSON object is being loaded with a play_time key-value pair. 

As it's inofficially for internal usage already possible to obtain the play_time, I'd like to request an implementation to the official public API as well.

An ETA for that would be nice as well!

Thanks in advance

**Comment by peppy** [comment]
Added to `get_user`.

**Comment by omkelderman** [comment]
added to docs now as well

**Comment by peppy** [comment]
thank you!
