### ISSUE TITLE
Beatmaps with star rating of 0 are not returned

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-api#222]
I'm not entirely sure that this is the cause for the error, but it happens on two 0-star mapsets:

https://osu.ppy.sh/api/get_beatmaps?s=791900&k=
https://osu.ppy.sh/beatmapsets/791900

https://osu.ppy.sh/api/get_beatmaps?s=832364&k=
https://osu.ppy.sh/beatmapsets/832364

**Comment by peppy** [comment]
Wasn't related to star rating, but rather cases where difficulty information was missing. These should now return correctly.
