### ISSUE TITLE
date returned on "get_user_recent" and "get_user_best" inconsistent

### ISSUE THREAD

**Issue by DMills94** [ppy/osu-api#223]
Recently I believe the `api/get_user_best` date returned was changed to be UTC+0

The date for `get_user_recent` however is still UTC+7, can these be made consistent?

Returned message for a `get_user_recent` call
![Image of issue](https://i.imgur.com/ycjLTnM.png)

(For some unknown reason I read the date as US?? It's 4th September, not 9th.)

**Comment by omkelderman** [comment]
> Recently I believe the `api/get_user_best` date returned was changed to be UTC+0

that is news to me, I thought everything throughout the API was still on +8. Welp this is gonna be rather confusing.....

**Comment by peppy** [comment]
They both look to be matching at this end. There's no difference in the code. Both are returned UTC+8.

**Comment by peppy** [comment]
Please reopen with actual evidence if you're seeing this happen.
