### ISSUE TITLE
Change description to indicate osu-web is for API v2

### ISSUE THREAD

**Issue by jxu** [ppy/osu-api#231]
Since https://github.com/ppy/osu-web is the home of API v2 and the current API is not being actively developed, the README or repo description should reflect that change and encourage users to post issues/feature requests in osu-web instead of here.

**Comment by jxu** [comment]
See discussion in #102, #218, #227, etc.

**Comment by peppy** [comment]
If you read into the discussion, you'd notice it is not ready for widespread consumption yet. Giving it more publicity is the exact thing I want to avoid doing until it is in a ready state.
