### ISSUE TITLE
Feature request: osz hash

### ISSUE THREAD

**Issue by wmpmiles** [ppy/osu-api#233]
Having a hash of the latest osz for a beatmapset would be extremely useful for verifying osz files that are being distributed via 3rd party methods. 

I believe the only current method for obtaining said hashes is through beatmap download request header data from the website, and as not all osz's are available to download a number of them are unverifiable as up-to-date.

This could be integrated into the existing get_beatmaps or could be given it's own call.

**Comment by peppy** [comment]
Hi,

We don't currently store this server-side in a format useful to you (we use osz2 hashes). Your best bet for now is checking date modified against `last_update` or checking the hash of each .osu file (which is already exposed via the API).
