### ISSUE TITLE
Add cover_url to /get_user

### ISSUE THREAD

**Issue by PalaBeaveR** [ppy/osu-api#234]
![opera_smuhkc6plr](https://user-images.githubusercontent.com/35870033/51439074-c6ba3700-1cbd-11e9-9ed8-f8396d9fefce.png)
You can find cover_url in json's located in profile page, but you can't get it from api. It's really annoying to parse entire html file just to get this url so please add it to api.

**Comment by peppy** [comment]
This will only ever be in the new api. Please check it's not already there (pretty sure it is) and make a feature request against osu-web.
