### ISSUE TITLE
Some replays unavailable even though they're in top100

### ISSUE THREAD

**Issue by Liam-DeVoe** [ppy/osu-api#235]
Multiple user's replays on the big black are not available.

https://osu.ppy.sh/api/get_replay?k=KEY&m=0&b=131891&u=2558286 and 
https://osu.ppy.sh/api/get_replay?k=KEY&m=0&b=131891&u=256802

({"error":"Replay not available."}), even though rafis is  \#11 on the leaderboards and happystick is \#61. I assume this is intended behavior; is there a specific reason this happens so it can be documented and added to the wiki?

**Comment by peppy** [comment]
In the past, we have had failures in replay upload or storage. I believe the underlying issues causing this have since been resolved, but there may be some historical scores which don't have replays as a result.
