### ISSUE TITLE
Grab current user activity ("Now Playing")

### ISSUE THREAD

**Issue by jack-avery** [ppy/osu-api#237]
I'm well aware of the previous issues opened about this topic;
https://github.com/ppy/osu-api/issues/37
https://github.com/ppy/osu-api/issues/143

... but I thought I would bump the topic with _another_.

I remember seeing peppy say in issue 37 that "this will change in the near future".
Is there any possibility of a "Now Playing" coming to the API?

**Comment by peppy** [comment]
We will definitely be supporting this, but it will likely come in the v2 api via osu-web.

Opening new issues for the same request is redundant, though.
