### ISSUE TITLE
feature request: user's top play in /get_user

### ISSUE THREAD

**Issue by kiranw0w** [ppy/osu-api#238]
The top play is pretty important in user's profile, because you can't always determine the skill by the raw_pp itself but with (example) best_play we would be able to determine what this guy is capable of.

**Comment by peppy** [comment]
Can't you just make a second api call?

**Comment by kiranw0w** [comment]
> 
> 
> Can't you just make a second api call?

It cuts in half my request limit, sure I could do that but with big cost.

**Comment by peppy** [comment]
This is best we can do for now. The score lookup actually adds a relatively large overhead, which is why it's in a separate request in the first place.
