### ISSUE TITLE
Add information regarding removed ranked beatmaps to get_beatmaps

### ISSUE THREAD

**Issue by lemoncove** [ppy/osu-api#241]
For example, [Despacito](https://osu.ppy.sh/beatmapsets/665562#osu/1408519) was subject to a DMCA takedown. Manually downloading the beatmap will yield no audio, which is an issue for services which find beatmaps for users to play. If an `audio_available` or similar field were added, such maps could be filtered out.

**Comment by peppy** [comment]
Addded `audio_unavailable` and `download_unavailable`. Please update wiki documentation.
