### ISSUE TITLE
/get_beatmaps/ wrong username for creator

### ISSUE THREAD

**Issue by Xferno2** [ppy/osu-api#246]
I did a /get_beatmaps/ request on this map https://osu.ppy.sh/beatmapsets/466254#osu/1147263 with those parameters  https://osu.ppy.sh/api/get_beatmaps?k=MYAPIKEY&b=1147263
 
The response was the following:
```json
[{
    "beatmapset_id": "466254",
    "beatmap_id": "1147263",
    "approved": "4",
    "total_length": "472",
    "hit_length": "459",
    "version": "Winter",
    "file_md5": "96d1ac6c27c8b82d3264abe23402567a",
    "diff_size": "4",
    "diff_overall": "8.9",
    "diff_approach": "9.3",
    "diff_drain": "6",
    "mode": "0",
    "approved_date": "2017-04-01 11:15:27",
    "last_update": "2017-03-19 23:57:12",
    "artist": "Kumagai Eri (cv.Seto Asami)",
    "title": "Winteright",
    "creator": "Itasha_S13",
    "creator_id": "3897366",
    "bpm": "175",
    "source": "\u97f3\u697d\u5c11\u5973",
    "tags": "music girl ongaku shoujo justability electro.muster kato yoshihal taishi cosmic record drum and bass dnb",
    "genre_id": "3",
    "language_id": "3",
    "favourite_count": "247",
    "playcount": "51952",
    "passcount": "4004",
    "max_combo": "2710",
    "difficultyrating": "5.726606845855713"
}]
```

The response states that the creator is **Itasha_S13** but on the website his/her name is **ItashaS13** with no underscore.
[![User](https://i.gyazo.com/7a61ad60821e986f3417d76f103196f4.png)](https://osu.ppy.sh/users/3897366)

**Comment by Liam-DeVoe** [comment]
Maybe interesting/relevant to note that the old website lists his past username as "Itasha_S13", but the new site lists his past username as "Samuel7331".

**Comment by peppy** [comment]
This is actually correct (well, intended). The creator name at the point of creating the beatmap is stored in the beatmap's metadata, and the API reflects this. If you want to get the most recent username, please use `creator_id` to look it up in a second request.
