### ISSUE TITLE
Many fields null for get_beatmap

### ISSUE THREAD

**Issue by Liam-DeVoe** [ppy/osu-api#247]
https://osu.ppy.sh/api/get_beatmaps?k=KEY&s=484 has null values in most of its fields:
```
"beatmapset_id": null,
"beatmap_id": null,
"approved": null,
"total_length": null,
"hit_length": null,
"version": null,
"file_md5": null,
"diff_size": null,
"diff_overall": null,
"diff_approach": null,
"diff_drain": null,
...
```

The beatmap page also fails to load (https://osu.ppy.sh/beatmapsets/484), and gives errors in the console.

Possibly related to https://github.com/ppy/osu-api/issues/130. I assume this also happens when using the `b=` parameter, but I don't know its beatmap id to check.

**Comment by peppy** [comment]
Fixed by deleting the set.
