### ISSUE TITLE
score_id is missing from get_user_best and get_user_recent

### ISSUE THREAD

**Issue by Adrriii** [ppy/osu-api#248]
This would be useful for storing player's scores on my end

**Comment by peppy** [comment]
Added. Please update wiki documentation if you can!

**Comment by peppy** [comment]
Oh sorry, I had to remove it from `get_user_recent`. The `score_id`s in the table that stores recent scores do not match what you'd expect them to be.

**Comment by Adrriii** [comment]
Oh alright, no problem !

**Comment by Liam-DeVoe** [comment]
Documentation updated (commit: 73a0dd6d734b0c5a0f48a3679466289322ff25a8)

Huh. Didn't know wiki commits don't hyperlink
