### ISSUE TITLE
pp is missing from get_user_recent

### ISSUE THREAD

**Issue by Adrriii** [ppy/osu-api#249]
This would prevent me from having to downlaod the beatmaps files and calc the pp on my server in the case of mods being applied

**Comment by Adrriii** [comment]
I've read this : https://github.com/ppy/osu-api/issues/93

But since now the server might handle it differently, the previous issue might be outdated.

**Comment by peppy** [comment]
This is still current. Please continue discussion there if necessary; this is a duplicate.
