### ISSUE TITLE
/get_beatmaps beatmapsets with over 500 beatmaps

### ISSUE THREAD

**Issue by Sandalot** [ppy/osu-api#251]
This beatmapset has 534 beatmaps https://osu.ppy.sh/beatmapsets/372271
If I was to make an API request for this set I'll only get 500 results. Is there an elegant way to request the next block of 500?

I'm making a beatmap "cache" that emulates official mirrors like https://bm8.ppy.sh/ and others with identical functionally. The main goal is to reduce the bandwidth demand at events like a lan party where speeds can be unbearable at times. I use this API to compare my caches database for updated maps and when relevant use https://osu.ppy.sh/web/maps/ for a more efficient use of bandwidth. Being able to fetch all the beatmaps in a set is important for this use case.

inb4 there is some way to already do this and I'm just stupid

**Comment by tybug** [comment]
use `&since` and pass the `approved_date` of the last beatmap of your response

**Comment by peppy** [comment]
Rest assured such sets will not appear too often. I'm adding a hard limit to difficulties per set to avoid this.

For the time being I'd just ignore such cases.
