### ISSUE TITLE
get_beatmaps doesn‘t show date submitted

### ISSUE THREAD

**Issue by Chromoxx** [ppy/osu-api#254]
Since it already shows the approval date and last update, it‘s kind of a shame that it doesn‘t show the date submitted. Would be pretty helpful for analysis.

**Comment by peppy** [comment]
Added, please update documentation if you can.

**Comment by jxu** [comment]
Does this address https://github.com/ppy/osu-api/issues/195?

**Comment by peppy** [comment]
Yep, will close.
