### ISSUE TITLE
Incorrect diff_size for converted mania maps

### ISSUE THREAD

**Issue by grumd** [ppy/osu-api#257]
Coverted mania maps return standard circle size instead of key count for mania
Example:
https://osu.ppy.sh/api/get_beatmaps?k=API_KEY&b=1562486&limit=1&m=3&a=1
https://osu.ppy.sh/beatmapsets/740641#mania/1562486

It should return diff_size: 7 instead of diff_size: 4.5

**Comment by peppy** [comment]
I'm not 100% sure we support this at a database level. @smoogipoo might know better than me (does osu-stable diffcalc correctly output convert key counts these days? do we need to run a reprocess?)

**Comment by smoogipoo** [comment]
Yeah it's not quite exact for converts, there's a few heuristics to determine the keys based on other difficulty attributes.

The actual amount of keys isn't populated in the DB at all at the moment, but we could maybe implement the heuristics via https://github.com/ppy/osu/blob/0e8517ebaedda65f1b3f30a134c911a3add99dbf/osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs#L48 in osu-web?

**Comment by grumd** [comment]
@smoogipoo https://github.com/ppy/osu-web/pull/3276/files
Not sure how helpful is this link to you, but I found this. osu-web already has some code to calculate it.

**Comment by smoogipoo** [comment]
Yeah that's the one we should be using. cc @nanaya

**Comment by peppy** [comment]
Closing this as not-planned in api v1 (the implementation is not so simple). It will 100% be there in api v2, which will have full documentation in the very near future.
