### ISSUE TITLE
randomize mp links

### ISSUE THREAD

**Issue by minwoo0jo** [ppy/osu-api#261]
As the tournament scene is growing bigger and bigger within osu, there's a recent trend that's been popping up in team tournaments, which is to use a program to find the opposing team's practice multiplayer lobby mp link via the api's /get_match request.

These programs will simply iterate through tens of thousands of the most recent mp links to find a lobby with the opposing team's user ids. This reveals a lot of information that these teams try their best to hide as it could give a big advantage over to the other team.

Although you could argue that teams can just practice in solo play or even offline, many teams find it invaluable to play together in a lobby where they can see each others' performances and figure out how to approach the upcoming match. Because of this, players are starting to move their practice multiplayer lobbies into other, unofficial servers just to get their practice in.

A lot of people that I've talked to are against teams using these programs, and usually, doing this isn't even allowed by the tournament staff, but unless the offending team confesses, it's nigh impossible to prove.

This problem could be fixed by randomizing future mp links. Another solution could be locking API requests for password protected multiplayer lobbies unless the API key belonged to a player who joined the lobby, but I believe that this would require more work to determine whether or not a lobby was password protected and whether or not the player participated in the lobby.

**Comment by peppy** [comment]
We will be adding a command to lock match history. Closing in favour of https://github.com/ppy/osu-web/issues/4491.
