### ISSUE TITLE
BPM = 0 on all difficulties of this beatmap with /get_beatmaps

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-api#265]
https://osu.ppy.sh/beatmapsets/577617#mania/1336842
You can see it on the website too
Screenshot:
https://i.gyazo.com/fbb0b229d8feb563116a886014792ccd.png

**Comment by peppy** [comment]
This beatmap has corrupt timing points (can also not be loaded in lazer). Should probably be fixed.

**Comment by peppy** [comment]
This has been resolved.
