### ISSUE TITLE
thumbnail for beatmaps

### ISSUE THREAD

**Issue by Citrom67** [ppy/osu-api#272]
I've been thinking about how to get thumbnails from /get_beatmaps, and I've come across the earlier issue about thumbnails but that method isn't working. (And I hope so that not I am stupid)
Because this gives back a 404 error https://s.ppy.sh/651507

**Comment by Liam-DeVoe** [comment]
Looks like the thumbnails are hosted under assets.ppy.sh now. `https://assets.ppy.sh/beatmaps/{set_id}/covers/cover.jpg` eg https://assets.ppy.sh/beatmaps/79498/covers/cover.jpg

Previous issue referenced: #26
