### ISSUE TITLE
Add request to get user's profile badges

### ISSUE THREAD

**Issue by willyosu** [ppy/osu-api#273]
**Proposal**
Add an api response to `api/get_user` to return a user's profile badges given a UID or username. This would be useful for a number of apparent reasons, but also for the ability for users to easily calculate BWS (a number used by tournaments to prevent rank sandbagging).

**Example Response**
```
[ ...
    {"badges"         : ["osu! World Cup 2018: 1st place (United States)", "LAN Dream Spring Irvine Party! 2018 Winner", ...] }
]
```

**Comment by peppy** [comment]
This is already returned in APIv2. Please use that instead.

https://docs.ppy.sh/#apiv2usersusermode
