### ISSUE TITLE
/get_user?u=username_old  acts the same as /get_user?u=username

### ISSUE THREAD

**Issue by Liam-DeVoe** [ppy/osu-api#280]
https://osu.ppy.sh/api/get_user?k=KEY&u=legendre_old and https://osu.ppy.sh/api/get_user?k=KEY&u=legendre both redirect to https://osu.ppy.sh/users/9868921 (legendre), even though a user by the name of legendre_old exists - https://osu.ppy.sh/users/709891. Querying for legendre_old should give legendre_old's profile.

Interestingly, https://osu.ppy.sh/api/get_user?k=KEY&u=legendre_ (adding an underscore) gives the profile of legendre_old.

**Comment by peppy** [comment]
Fixed.

**Comment by Magnus-Cosmos** [comment]
This still seems to be an issue, https://osu.ppy.sh/api/get_user?k=KEY&u=JakisRandom_old still redirects to Jakisrandom instead of JakisRandom_old

**Comment by peppy** [comment]
This is actually intended – we don't index _old users or expose them in any way. The idea is they will contact us if they want to seriously play again and we'll fix their usernames.

**Comment by Liam-DeVoe** [comment]
That's disappointing if it means that these users are intended to be inaccessible via the api. They are already accessible with a direct link (https://osu.ppy.sh/users/JakisRandom_old), so I don't see the point in excluding them from the api.

**Comment by peppy** [comment]
We will consider removing the direct links and placing their accounts in a more archived state. Thanks for the feedback!

**Comment by Liam-DeVoe** [comment]
A larger distinction between normal and `*_old` accounts would be appreciated — I didn't realize you considered them to be in a different category of users.
