### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Moebytes** [ppy/osu-api#282]
-

**Comment by ThePooN** [comment]
You cannot seach for multiplayer lobbies in any way. You're supposed to get such IDs by creating the lobby with !mp make (see [Tournament Management Commands](https://osu.ppy.sh/help/wiki/osu!tourney/Tournament_Management_Commands/)), or get it from BanchoBot when you join a lobby.

**Comment by Tenpi** [comment]
> You cannot seach for multiplayer lobbies in any way. You're supposed to get such IDs by creating the lobby with !mp make (see [Tournament Management Commands](https://osu.ppy.sh/help/wiki/osu!tourney/Tournament_Management_Commands/)), or get it from BanchoBot when you join a lobby.

Thank you, I was not aware. I have never used BanchoBot to join a lobby.
