### ISSUE TITLE
Feature Request: Add UR (unstable rate) to /api/get_match

### ISSUE THREAD

**Issue by Acrith** [ppy/osu-api#284]
Hello, what are the chances that osuapi can contain unstable rate (UR) of players in multiplayer room after map is played? I'd like to get that information due to tools I am working on - like for example custom profiles, or gamification projects (especially in osu!taiko), where unstable rate is a clear indicator how comfortable a play was for a certain player.

In current circumstances, we can't even get informations when we hover over graph in multiplayer, and multiplayer is the only way to automatically validate players' performance without screens or replays.

**Comment by Liam-DeVoe** [comment]
From what I understand, ur isn't stored anywhere, but calculated clientside (which is why you can only see it after watching an entire replay)

**Comment by Acrith** [comment]
Let me explain real quick. Everytime we play a beatmap, at the end of it we can hover over the graph and check our error and unstable rate. Those values persist in memory for current session I believe.

Can't client just send the final value of UR to server just like it does with score, number of 300s, 100s, misses, FC status, etc? I know, sure - there isn't probably a variable that stores it in game - but the final results stays in that memory anyway. If we - for example, play a map in multiplayer, and leave after map from game and check the local score - we still can check its UR and Error without watching replay - and it's hella tedious to do so.

So my question is - couldn't we send that value along with score and rest of parameters into API?

**Comment by peppy** [comment]
This is not stored. You would need to download the replay and calculate this yoruself.
