### ISSUE TITLE
Help to download beatmaps by ID

### ISSUE THREAD

**Issue by frixaco** [ppy/osu-api#288]
Hello, everyone
I have a list of my beatmaps' IDs in text file and want to download the beatmaps by their ID. The reason is that when I was reinstalling Windows all my beatmaps got corrupted, but I managed to get each beatmaps' ID.
I'm beginner in programming (Python) but did a few attempts using `requests` library with no success.
Can someone give an example or a direction where I should look/research to download a beatmap by its ID, please?

**Comment by ThePooN** [comment]
This is not a supported use case.

**Comment by frixaco** [comment]
> 
> 
> This is not a supported use case.

Ok, I edited it

**Comment by ThePooN** [comment]
What I meant is, the API doesn't support downloading beatmaps.

**Comment by FrixaCoder** [comment]
Oh. So there's not any way to (write a script) mass download beatmaps by their IDs?

**Comment by frixaco** [comment]
🎉I found a solution!
I'll leave it here just in case.
All I needed to do was to import my cookies from my browser (check out `browser-cookie3` library for Python). The idea is that you need to be logged in to download a beatmap. One option: just use the cookies from the browser where you are logged in to osu!:

```py
import browser_cookie3
import requests

cj = browser_cookie3.firefox()
url = 'https://osu.ppy.sh/beatmapsets/1012634/download'
r = requests.get(url, cookies=cj)

with open("map_name.osz", 'wb') as f:
    f.write(r.content)
```

Second option: you can also programmatically login to osu!, parse get the cookies and attach the cookies when downloading the beatmap file.
