### ISSUE TITLE
Osu Api Google Sheets

### ISSUE THREAD

**Issue by ghost** [ppy/osu-api#291]
I would like to use osu api to get my user data and recent scores ect on a google sheet. I have added the importjson function with a script but cant figure out how to format it with the api access token. I am fairly competent at google sheets, but clueless beyond that. Any help appreciated.

**Comment by Liam-DeVoe** [comment]
Do you just need the url to retrieve the json from? if so, this is the format: `https://osu.ppy.sh/api/ENDPOINT_NAME?k=API_KEY&PAREMETER=VALUE&PARAMETER=VALUE` (etc)

To retrieve your recent scores as json, use: `https://osu.ppy.sh/api/get_user_recent?k=API_KEY&u=YOUR_USER_ID`, replacing the capitalized words with the necessary values.

**Comment by ghost** [comment]
I think I got the hang of it now, just needed help with the format thx a lot.
