### ISSUE TITLE
rank history

### ISSUE THREAD

**Issue by Maxluli** [ppy/osu-api#293]
i did search on the wiki page and in all the issues and i did'nt find any talking about getting the rank history of a player to make a graph like on the osu website.

**Comment by Maxluli** [comment]
sorry there is documentation for get_user_best my bad, but for the images and other function there is a lack of documentation is it normal?

**Comment by Liam-DeVoe** [comment]
duplicate of #215 ?

**Comment by peppy** [comment]
Should probably be requested against [ppy/osu-web](https://github.com/ppy/osu-web) instead (in the new api version).
