### ISSUE TITLE
get_replay by score id

### ISSUE THREAD

**Issue by Liam-DeVoe** [ppy/osu-api#297]
would be nice to be able to retrieve replay data from a replay id through the api. I know there's `http://osu.ppy.sh/scores/osu/SCORE_ID/download`, but unsure if that's the approved way to automatically download replays.

**Comment by peppy** [comment]
I've added this, via `s` parameter. Note you will still need to provide the game mode via `m`.

**Comment by Liam-DeVoe** [comment]
Thanks. Documentation added.

Any reason we can't download replays by restricted users? You can still do so through the website url `/scores/osu`, but not through this api call. For instance, `https://osu.ppy.sh/scores/osu/2995111371/download` vs `https://osu.ppy.sh/api/get_replay?k=KEY&s=2995111371&m=0`. Replay download links from [this osureport thread](https://old.reddit.com/r/osureport/comments/f1o1it/osustd_noobas2283_auto/) on a recently restricted user.

**Comment by peppy** [comment]
that is actually a bug. they should not be available. will look into fixing

**Comment by ThePooN** [comment]
Sounds lame to me. Post-restriction replay analysis can still be useful.

**Comment by Liam-DeVoe** [comment]
I agree. Was hesitant to bring it up here for fear of this exact scenario. It has been tremendously useful to be able to look at month or year old osureport threads and  download and analyze the replays — it is often the very fact that their player got restricted that makes a replay worth looking at.

**Comment by peppy** [comment]
Will discuss this internally. Maybe it's fine if it's API-level. The main thing is we don't want restricted users getting undue attention for breaking the game (becaues there is an audience for that kind of thing, unfortunately).

**Comment by peppy** [comment]
I've allowed getting such replays from apiv1 via score_id (only). We'll keep it this way for the time being.

**Comment by Liam-DeVoe** [comment]
I appreciate it!
