### ISSUE TITLE
api occasionally returning null

### ISSUE THREAD

**Issue by dz-ss** [ppy/osu-api#298]
Once in a while (sometimes half the time), the api returns null instead of what it's supposed to return. This only started happening within the past 24 hours.
e.g. if you reload this a bunch of times, it'll return null once in a while https://osu.ppy.sh/api/get_beatmaps?k=<api_key>&m=0&since=2020-02-10%2020:00:00
<img width="205" alt="api return none" src="https://user-images.githubusercontent.com/52870410/74888538-38930300-534c-11ea-9340-911d20ff588e.PNG">

**Comment by arily** [comment]
I got the same problem.

**Comment by Liam-DeVoe** [comment]
I've also been seeing this behavior (since `2020/02/19 06:54:06` EST). I can only replicate the behavior on the `get_beatmaps` endpoint manually, though I only tested a few others.

**Comment by peppy** [comment]
Thanks for pointing this out. The database server responsible for the API was struggling somewhat – has been resolved now.
