### ISSUE TITLE
/get_user historical global rank

### ISSUE THREAD

**Issue by jxu** [ppy/osu-api#299]
At least the past 90 days which is viewable on a user's profile

**Comment by aspriddell** [comment]
This functionality already exists in v2 (so it probably won't be coming to v1)

It can be obtained from `/api/v2/me/{mode?}` or `/api/v2/users/{user}/{mode?}` (but you'll need an OAuth client registered for this). You can find the data models for these endpoints in the [osu!lazer repo](https://github.com/ppy/osu/blob/master/osu.Game/Users/User.cs)

Note: as of posting access to the second endpoint is not available, but there is an approved [PR](https://github.com/ppy/osu-web/pull/5700) that will enable it.

**Comment by jxu** [comment]
This is the same situation as with Lazer. "It's coming in Lazer" but Lazer isn't out yet so we get no features for an indefinite amount of time

**Comment by jxu** [comment]
@aspriddell btw do you know how much history is given? If it is enough then we could possibly reconstruct historical leaderboards

**Comment by aspriddell** [comment]
@jxu I think you get the equivalent data to the site (the last 90 days in a list of numbers) when you lookup a user (which you can now do).

**Comment by peppy** [comment]
@jxu apiv2 is already "out" and usable. please use it for this.
