### ISSUE TITLE
How do Services like osu!Skills get all user Plays?

### ISSUE THREAD

**Issue by Eeveelution** [ppy/osu-api#301]
Do they even use the osu!api for that? I was wondering because i wanted to create something simmiliar to a performance ranking and it would be convinient to get all Scores set by a Player.

**Comment by peppy** [comment]
For top players you could consider using data.ppy.sh, but please read the licence.

We don't support getting all plays for a user outside of what is currently available. New api endpoints will come online on apiv2 in the near future which may change this.
