### ISSUE TITLE
scoreV2 in /api/get_user_recent ?

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-api#302]
request: https://osu.ppy.sh/api/get_user_recent?k=key&u=4196808&limit=50

i found this problem 10 min ago, when my bot not posting scores for a while

api data (536870921 = +ScoreV2HDNF)
![chrome_ArgpImu8VD](https://user-images.githubusercontent.com/21735205/77233664-82853800-6bdb-11ea-8f3d-d3919582a59d.png)
on site (osuplus extension)
![chrome_IAAw7yGkcf](https://user-images.githubusercontent.com/21735205/77233668-83b66500-6bdb-11ea-8ff4-c22e3127d99b.png)

**Comment by peppy** [comment]
yes, this is to be expected. please adjust your code.
