### ISSUE TITLE
querying get_scores with score-ID

### ISSUE THREAD

**Issue by omkelderman** [ppy/osu-api#304]
With the recent introduction of the new score display page (https://twitter.com/ppy/status/1263083380951793664) I would like to query score information with a score ID as starting point, as the url of that page contains the score ID and nothing else. (for example: grab more info about that score whenever a user posts a link to that page somewhere)

So exactly the same as the `s` parameter that right now already exists for get_replay.

Furthermore since now the only input I have is score ID I would also like a beatmap_id in the result object so I know which map a score is from purely based on (for example) the url of that score display page.

**Comment by peppy** [comment]
more likely to see this on apiv2.

**Comment by omkelderman** [comment]
feel free to correct me, but I made this issue under the assumption that these would be very easy changes. Surely filtering on score id shouldnt take too much effort? get_replay already does it, and im assuming its the primary key of the table in the database (assuming the scores are stored like that in a database).
also with each score-object surely there must be a reference to a beatmap somewhere? if thats the hash instead of the id, im also fine with that, just something that tells me which map and happy.

as for apiv2, id love to use it, but unless im missing something there isnt really an easy way for machine to machine communication yet. I have to go through the whole oauth flow to get a token and build in refresh logic since that token can expire. From what I've seen there is no simple "api key" like authentication on api v2

**Comment by peppy** [comment]
What is "machine to machine communication"?

**Comment by peppy** [comment]
Sounds like you're just being lazy.

And yes, it may be an easy change, but continuous easy changes give legacy sytstems more reason (in users' eyes) to exist and you're gonna get pissed when i turn it off. So no, sorry. APIv1 is basically feature locked. Please make this request on osu-web.
