### ISSUE TITLE
/get_user_recent Addition

### ISSUE THREAD

**Issue by hmaltr** [ppy/osu-api#307]
On endpoint "/get_user_recent" is it possible to add an array of mods enabled? *alternative to already existing "enabled_mods"*
*(mode names like ["Hidden", "HardRock"] )* 

It can be useful for some applications that doesnt want to deal with enumerators.

**Comment by Liam-DeVoe** [comment]
Are you suggesting the names should be added in addition to the integer `enabled_mods`? I don't see the point when you can convert between the two; see https://github.com/ppy/osu-api/wiki#mods

**Comment by hmaltr** [comment]
Yeah, I was saying that.

Though the case in my application it gets messy pretty easily, when a lot of mods gets enabled.
*like enabling every possible difficulty increasing or decreasing mods*.

So adding something like that may also help other people.

**Comment by peppy** [comment]
you need to read up on bitwise flags. it should not be any different handling the existing `enabled_mods` or an array.
