### ISSUE TITLE
Rate Limiting is based on IP, not API Key

### ISSUE THREAD

**Issue by ayyEve** [ppy/osu-api#309]
I run a server with many people running bots, and the osu api rate limited by ip.

So even if any one key is not using enough to rate limit, all keys together are causing all keys to be rate limited.

For instance, one user made two requests, then got rate limited.

Let me know if there's any more info you need, or if there's anything I can do to help.

**Comment by peppy** [comment]
This means you are hitting our server protection rate limits, which are separate from API rate limits. This is intended and we can't change it, sorry.
