### ISSUE TITLE
/get_user_best returns 'X' instead of 'SSH' in rank field

### ISSUE THREAD

**Issue by blinchk** [ppy/osu-api#313]
So, I have a next request (limit 3, my username at osu! and standard mode) and response.
![image](https://user-images.githubusercontent.com/49353043/104135483-cc751f80-53a1-11eb-8d6b-4c497fab8590.png)

**On line 36 of response instead of rank 'SSH' returns 'X'.**

**Comment by Liam-DeVoe** [comment]
I can't find where this is documented, but I'm pretty sure this is intentional. From osu-lazer (https://github.com/ppy/osu/blob/master/osu.Game/Scoring/ScoreRank.cs):

```
        [Description(@"S")]
        S,

        [Description(@"S+")]
        SH,

        [Description(@"SS")]
        X,

        [Description(@"SS+")]
        XH,
```

SS is X and SSH is XH.

**Comment by blinchk** [comment]
@tybug, thank you for answer!
