### ISSUE TITLE
issue with map data, maxcombo== null

### ISSUE THREAD

**Issue by thr3xi** [ppy/osu-api#314]
I have seen that this has been an issue before but haven't found a solution to fixing my map.
https://osu.ppy.sh/beatmapsets/1383840#osu/2882226.
find out about the issue while using tillerinobot and looked up this issue.
if someone could shed some light on my issue it would be greatly appreciated.
the precise beat map is the 4.70-star version, normal difficulty.

if any other data/info is needed I would be ready to get it

**Comment by peppy** [comment]
We don't run tillerino bot.

**Comment by thr3xi** [comment]
the problem is not with the tillerino bot. its only the reason I found out that I had a problem with "maxcombo==null"
and that seem to be a problem with API
the problem really has nothing to do with tillerino

**Comment by peppy** [comment]
How are you confirming this?

**Comment by thr3xi** [comment]
I am not good at looking up the different things on the map. but the bot refers to an issue posted on here about maxcombo, all I really need is help to figure out how to check /fix the problem.

**Comment by peppy** [comment]
It looks fine from our end. Please contact the other service as it is not an issue at our end.
