### ISSUE TITLE
Retrieve a player by rank

### ISSUE THREAD

**Issue by AuracleTech** [ppy/osu-api#315]
Website and apps like osuskills, tillerino, osudaily and many more already do that, but indirectly, they leech data left and right from the api to do their business.

I'm making a bot called [Cake](https://github.com/AuracleTech/Cake), basically Tillerino, and I noticed all websites use data leeching & web scrapers to retrieve rank ladder & player's rank.

Adding this ironically would save osu on data bandwidth. Instead of leeching & scraping tons of data we could get what we want directly.

Related feature request
- https://github.com/ppy/osu-api/issues/181
- https://github.com/ppy/osu-api/issues/102
- https://github.com/ppy/osu-api/issues/245
- https://github.com/ppy/osu-api/issues/215
- (Include rank, ask for filters) https://github.com/ppy/osu-api/issues/290

**Comment by Liam-DeVoe** [comment]
duplicate of #181

**Comment by AuracleTech** [comment]
> duplicate of #181

I saw I was editting, this is an ongoing issue that has tons of duplicate.
I checked osu-web at first because osu-dev discord doesn't have #osu-api so I expected there wasn't a git only for osu-api either.
