### ISSUE TITLE
Why do application tokens expire so quickly?

### ISSUE THREAD

**Issue by kaname-png** [ppy/osu-api#319]
I have generated a token with the endpoint [https://osu.ppy.sh/oauth/token](https://osu.ppy.sh/docs/index.html?javascript#client-credentials-grant), but I see that its expiration is in 1 day, this is very little, to be an application token, what can I do to not have to be generating a token every day and configure it in my code?

**Comment by peppy** [comment]
Please use the refresh token. Google oauth refresh tokens (it's a very standard process).

**Comment by kaname-png** [comment]
> Please use the refresh token. Google oauth refresh tokens (it's a very standard process).

This endpoint does not give a refresh token.

**Comment by peppy** [comment]
It does. You can find full documentation here: https://osu.ppy.sh/docs/index.html#authorization-code-grant

**Comment by kaname-png** [comment]
It does not

![image](https://user-images.githubusercontent.com/56084970/130006541-df4ffdad-5e28-4643-9979-526da1a1b0de.png)
