### ISSUE TITLE
When using "Accuracy" win condition, BanchoBot returns score

### ISSUE THREAD

**Issue by kiwec** [ppy/osu-api#321]
On osu! stable, after players have finished a map in a lobby where the win condition is set to "Accuracy", BanchoBot gives scores instead of giving accuracy (or a score based on accuracy).

Expected for 98.72% accuracy:
```
BanchoBot: kiwec finished playing (Score: 9872, PASSED).
```

But instead, received:
```
BanchoBot: kiwec finished playing (Score: 2483850, PASSED).
```

Not sure if this also affects the "Combo" win condition.

**Comment by peppy** [comment]
I guess you're talking about the log output in chat? How important is it that this is resolved for you? i believe you can still get the full stats of each score from the API directly.

**Comment by kiwec** [comment]
> I guess you're talking about the log output in chat?

Yes.

> How important is it that this is resolved for you? i believe you can still get the full stats of each score from the API directly.

Not very important with that tip, I'll close this issue. I forgot `/api/get_match` gave detailed information - last time I tried I was fetching scores from user profiles, and that didn't sync well.
