### ISSUE TITLE
Add guest mapper in result

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-api#329]
For example:
`[{"beatmapset_id":"205095","beatmap_id":"541318","approved":"1","total_length":"132","hit_length":"130","version":"Satellite's Hard","file_md5":"a76ca6263b1f173e9ff18f8209fdd5c7","diff_size":"3.5","diff_overall":"6","diff_approach":"7","diff_drain":"5","mode":"0","count_normal":"104","count_slider":"212","count_spinner":"2","submit_date":"2014-08-21 15:50:38","approved_date":"2015-01-22 05:40:48","last_update":"2015-01-15 04:51:44","artist":"Kawada Mami","artist_unicode":"\u5ddd\u7530\u307e\u307f","title":"Wings of Courage -Sora o Koete-","title_unicode":"Wings of Courage -\u7a7a\u3092\u8d85\u3048\u3066-","creator":"Momovely","creator_id":"1713512","bpm":"160","source":"\u84bc\u306e\u5f7c\u65b9\u306e\u30d5\u30a9\u30fc\u30ea\u30ba\u30e0","tags":"sprite opening ao no kanata four rhythm beyond the sky into the firmament lecana quilt shirakai satellite dagger-gazel","genre_id":"3","language_id":"3","favourite_count":"438","rating":"9.45275","storyboard":"0","video":"1","download_unavailable":"0","audio_unavailable":"0","playcount":"107910","passcount":"14135","packs":"S392","max_combo":"579","diff_aim":"1.55237","diff_speed":"1.48391","difficultyrating":"3.15508"}]`

In this result, creator is Momovely, but in fact, creator is Satellite
`"creator":"Momovely","creator_id":"1713512"`

modify the results or add some fields, like this
`"creator":"Satellite","creator_id":"1661227"`
or
`"creator":"Momovely","creator_id":"1713512","guest_creator":"Satellite","guest _creator_id":"1661227"`
or
`"set_creator":"Momovely","set_creator_id":"1713512","creator":"Satellite","creator_id":"1661227"`

**Comment by peppy** [comment]
Please use the v2 api for this.

**Comment by wanjiaXG** [comment]
> Please use the v2 api for this.

OK
