### ISSUE TITLE
osu://mp/ no longer works on osu! stable

### ISSUE THREAD

**Issue by kiwec** [ppy/osu-api#330]
Reference: https://github.com/ppy/osu-api/wiki#osu-url-schema

Using `osu://mp/` or `osump://` links don't make the client join the lobby. 
It starts the game (if not started yet), but doesn't enter the lobby. 
This is while either the tournament `match_id` or the bancho invite IDs.

The bancho invite IDs work fine in-game, by sending a `[http://osump://invite_id/ click here]` message.

You can test the "join" links on https://osu.kiwec.net/lobbies/ - without that URL scheme, people have to log in to the website, start osu!, go back to the website to request an invite, and then find the invite in game PMs, which is a bit of a hassle compared to just 1 click.

**Comment by peppy** [comment]
It doesn't look like this was ever supported, and the wiki is listing it incorrectly.

We'll take a look at whether it can be quickly added, but I get the feeling it won't be so simple as it would require delay logic until bancho has connected if the link is clicked before the client has started.

**Comment by peppy** [comment]
I've added support for `osu://mp/` as per the wiki documentation. It should be usable in the next cutting edge release.

**Comment by FujiwaraSatomi** [comment]
I checked today with stable and cutting edge and neither worked. Is this api not working anymore? And if it is not working, why not remove it from the list?

**Comment by peppy** [comment]
Can you provide a video showing what you are doing / expecting to work?
