### ISSUE TITLE
max_combo is 0 for every single map

### ISSUE THREAD

**Issue by omkelderman** [ppy/osu-api#334]
Recently api v1 started giving a `max_combo` value of `0` for every single beatmap. Including ranked ones.

I suspect this has something to do with whatever happened behind the scenes on https://github.com/ppy/osu-web/issues/10566 but im a bit confused as this time it seems to affect every single beatmap and not just graveyarded maps as in that issue.

**Comment by peppy** [comment]
Should be better now, thanks for pointing this out.
