### ISSUE TITLE
Searching Users/Beatmaps

### ISSUE THREAD

**Issue by kkartaltepe** [ppy/osu-api#5]
As an osu-api enabled application I want to be able to search through users/beatmaps at least as effectively as I can on the osu! website.

So searching for users by partial name (similarly to the autocomplete when searching users on the website shows names that are close).

And Searching beatmaps by all or most of the search criteria available on osu.ppy.sh/p/beatmaplist

--Edit-- Postponed until someone has an real use for it. Just add a comment if you plan on using this feature should it be implemented.

**Comment by SirCmpwn** [comment]
I would like search functions. My use-case is for [osu!web](http://www.drewdevault.com/osuweb/), I want to make it so that you can search for a beatmap instead of having to drag-and-drop it.

**Comment by SirCmpwn** [comment]
I also have an IRC bot that I'd like to add beatmap searching to.

**Comment by ReDFoX43rus** [comment]
Peppy, as I understood: If I have plan of using search API you will give it to me?
Sorry for misunderstanding, Im bad at English

My plan is: Android application with stats and beatmaps (download, extract music/image etc.)
1st step (stats) is ready now. So it'd be nice if you implement beatmap search API

Thanks!

**Comment by jsw1174** [comment]
I manage a website for an internet radio station which plays some music that is also playable on Osu.

My use case for this type of functionality involves being able to tie together the songs that the station plays (and are listed on my website) to songs which our listeners might be able to play on Osu.  To do this, I need to be able to search via a string i.e. a song title.

Ultimately this could drive more traffic to your platform, it's a win-win.

**Comment by Phxntxm** [comment]
From what I've gathered, to request a searching feature made available to us we need to request that here? I have a Discord bot that I want to integrate Osu commands on, and with no way to search for beatmaps (minus actually logging in and web scraping) it requires all users to have to provide a beatmap ID for searching up scores on a beatmap.

Considering the steps needed for an end user to find the beatmap ID from searching the site, this can be a hassle for people who might not know what they are doing. The way I design this is to be idiot proof; without a search feature for beatmaps it makes that impossible to do atm (again short of web scraping).

**Comment by tsbreuer** [comment]
Yeah. i'm using osusearch.com on AutoHost bot, but i'd love to have an API part for searching for beatmps (Per gamemode (std/tai/etc), ranked/unranked/loved, star difficulty ranges, etc.

**Comment by christopher-dG** [comment]
Echoing a duplicate issue I opened: 

> I wrote a [reddit bot](https://github.com/christopher-dg/osu-replay-linker-bot) that gets beatmap links from score posts but it needs to look at the player's recent plays to get the beatmap ID which isn't quite as reliable as it could be. It would be much easier if I could search by beatmap/song name, the same way you can on the main website.

**Comment by ekgame** [comment]
http://osusearch.com/ has a nice, but undocumented API for searching beatmaps.

**Comment by tsbreuer** [comment]
Adding to ek's comment, you can document it yourself by testing the options and looking at the url bae.

**Comment by jy-roda** [comment]
Hi there. Even if using osusearch is possible, I don't really consider it as a solution. Having the possibility to search for beatmaps from the api would be great, and I brought a use case with me.
Because I have plenty of songs in my iTunes library, and that I do not want to search for each of them manually, i would like to make a tool that will give me a list of beatmaps when given the list of my library contents. Of course, I will try to make importing lists from other libraries possible.

Thanks

**Comment by tsbreuer** [comment]
Its not a solution. Its a temporary patch until we get the proper tool.

Should be possible to do this on lazer (And if not, i'll hop myself in into the api and write it myself (since open-source), when writing autohost).

**Comment by superloach** [comment]
I'd like this, too.
Use: Discord Bot
Ability to help: probably not, sorry. (I could help pushing the new api to [osu_apy](https://github.com/albinohat/osu-apy), though)

**Comment by lukeacat** [comment]
This would be very awsome! I also have  uses, Discord Bot and a website.

**Comment by ignissak** [comment]
I'd really like to see this feature in future, I want to implement it in my discord bot.

**Comment by heagan01** [comment]
I want to see this feature in action, I want to make a beatmap searching website with all of the json object displayed

**Comment by peppy** [comment]
I believe this is already available via api v2. As such I'm closing it here. Please take a look at consuming our newer API if you want this functionality!

**Comment by muumif** [comment]
ik this is closed but there still isnt this kind of feature in the api v2 or it just isnt documented. making a website that takes anime from mal and searches for the osu song

**Comment by Liam-DeVoe** [comment]
For searching users you can use https://osu.ppy.sh/docs/index.html#search.

For searching beatmapsets there's https://osu.ppy.sh/docs/index.html#beatmapsetssearchfilters but it's not documented yet. I've implemented the basic `query` option for beatmapset searching [in my api wrapper](https://github.com/circleguard/ossapi/blob/e91631b38f808c8cbe1e071638ebae8d2ed80266/ossapi/ossapiv2.py#L1186-L1197) if you'd like to use that as a reference, though I'm also waiting for it to be documented before implementing all query options.

You should be able to guess the available query options pretty easily though, as they correspond to the url params on https://osu.ppy.sh/beatmapsets.
