### ISSUE TITLE
mods for /get_scores

### ISSUE THREAD

**Issue by Tillerino** [ppy/osu-api#70]
On the website, one can display the nomod top 50 scores for any beatmap. It would be great if we could get the same thing in the api. Arbitrary combinations of mods like in the client for supporters would be amazing.

**Comment by peppy** [comment]
Please document this addition (&mods=xxx, no argument = no filter).

**Comment by hypereddie** [comment]
I've [put it on the wiki](https://github.com/peppy/osu-api/wiki#apiget_scores), but I can't test it at the moment..someone else will have to do that.

However, I wasn't sure what xxx is in this case. Is it the combined bitwise enum ? (ex; specifying 24, or `8 | 16`, would filter for Hidden and Hard Rock)

**Comment by peppy** [comment]
Yes, it works like all other mod specifications in the API.

**Comment by Tillerino** [comment]
mods=0 behaves like no argument, so there's no way to get nomod-scores.

**Comment by peppy** [comment]
Please try again.

**Comment by Tillerino** [comment]
Lol, that 91 second reaction time. Everything is as expected now.
