### ISSUE TITLE
map star rating when using mods

### ISSUE THREAD

**Issue by Sakisan** [ppy/osu-api#81]
Hi

I am developing a web application to break down and compare players' pp.

example: http://puu.sh/djk6g/e6edba9f21.png

Most properties that vary in function of the mods being used can be easily calculated: bpm, approach rate, ...
But the star rating cannot. Therefore it would be nice if it could be provided with the /api/get_user_best records.

Thanks for your consideration

Edit: the application is now running @ http://pp.sakisan.be/

**Comment by Sakisan** [comment]
+ /api/get_beatmaps doesn't take a 'mode' parameter, so the star ratings for taiko, CtB and mania can't be queried.
(adding star rating to /api/get_user_best would solve this as well)

**Comment by FullTablet** [comment]
This would be useful for this as well https://osu.ppy.sh/forum/t/322126/start=0
That way all the required information would be obtained with 1 API call, instead of having to call for get_user_best once, and then calling for each beatmap for the star rating.

**Comment by ApolloFortyNine** [comment]
My solution to this was to just store in another table all the beatmap information for every map in people's top 50. There aren't that many, so the total table size right now is almost 7MB with 33k beatmaps in it. Takes something like 10ms to return a request from it, so I think it's a better idea than increasing the size of everyone's API calls.

**Comment by Sakisan** [comment]
The issue is you can't get the star rating for a map for a given set of mods.

**Comment by omkelderman** [comment]
hmm, but i think get_user_best is not the right place to put them. Its a property of a map, not of a play. Im not sure how but i think the best place to put this is somewhere in get_beatmaps

**Comment by ApolloFortyNine** [comment]
I'm pretty sure the star rating with mods is easily calculated, if you just compared a couple scores in osu . Also, it wouldn't matter to be slightly off with your calculations as it just doesn't matter.

**Comment by Sakisan** [comment]
No it's not easily calculated. When I asked Tom about this he suggested me to post an issue here. Also deducing it by comparing them with other scores defeats the purpose of using those ratings in other comparisons, they would be meaningless.

I'm suggesting ```get_user_best``` because scores already include the set of mods that were used. Including all permutations in the ```get_beatmaps``` records seems like a lot of unwanted information, maybe with specific request parameters, but that makes it complex to implement and document correctly. But sure that can work too.

**Comment by omkelderman** [comment]
I still think it shouldnt be put in `get_user_best` or any thing that outputs a score. Simple because it is not a property of a score, but a property of a beatmap.

In my opinion it will get weird and complex do document corretly if you add the star rating to an score-object.

At the moment `get_beatmaps` provides a methods to get star rating of all the modes on every map. Even converted onces. So the only thing missing from `get_beatmaps` is a way to know the star rating for certain mods.

If thats done, its simply selecting the right value depending on which mod used in the score-object.

But you are right that this would probably add unwanted information to `get_beatmaps`, because if you want to include every possible combination of mods that can be used, that list might get kinda long.
But if you include a "used mod"-parameter to `get_beatmaps` that defeats the purpose of caching `get_beatmaps`-calls... Idk, im not sure yet what to think about it. Lets see if some osu-dev gets an uber-smart idea :P

**Comment by ApolloFortyNine** [comment]
I'm pretty sure stars don't directly correlate to PP values, correct? That's why I was saying it doesn't matter if you calculate the star values a little off when using guesstimated mod multipliers.

I know it's 'close,' but I don't think it's an exact relation.

**Comment by Sakisan** [comment]
Thanks for your suggestion Apollo, but for some applications guesstimates won't do.

omkelderman, we're on the same page. I'm just a bit afraid including the calculated star rating may be already quite a time consuming job for an osu-dev. Having a practical way out of this could be just what they need. *hope*

**Comment by ApolloFortyNine** [comment]
The star ratings seem rather useless, but since you seem set on keeping your intentions secret, so be it.

**Comment by omkelderman** [comment]
> I'm just a bit afraid including the calculated star rating may be already quite a time consuming job for an osu-dev.
i dont think we should worry about that ^^

**Comment by omkelderman** [comment]
I'm gonna bump this with a new proposal.

Currently the `/api/get_beatmaps` response looks like this:
`/api/get_beatmaps?k=*key*&b=831241`
```
[{
    "beatmapset_id": "379783",
    "beatmap_id": "831241"
    ...
    "difficultyrating": 8.498066412629289
}]
```

I propose a new query-parameter, lets call it `includeModsStarRating` for the purpose of this proposal.
`/api/get_beatmaps?k=*key*&b=831241&includeModsStarRating=1`
```
[{
    "beatmapset_id": "379783",
    "beatmap_id": "831241"
    ...
    "difficultyrating": {
        "0": 8.498066412629289,
        "2": 7.743339332125088,
        "16": 9.14498348567517,
        "64": 11.920443634045595,
        "66": 10.866619934510078,
        "80": 12.812871408568416,
        "256": 6.600522848166877,
        "258": 6.010979170536226,
        "272": 7.110949441876061,
    }
}]
```
(or keep the old value there and add the dict to a new property and exclude the nomod one out of the dict)

If you're properly caching `/api/get_beatmaps` responses, you now have a dict you can query to get the correct star-ratings for each mod-combo that affects star-rating.

Oh and ofc this should then also works accordingly when requesting different modes 😄

**Comment by VostokSisters** [comment]
Cool idea!

**Comment by ThePooN** [comment]
Has since been resolved with `/get_beatmaps?mods=X` and properties such as `difficultyrating` in response. This should be closed.
